# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Side7"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"

auto_page: 1

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1

session: Cookie

mailer_address: 'noreply@side7.com'
datetime_format_short: '%d %b %Y, %I:%M %p'
datetime_format_long: '%A, %d %B, %Y @ %I:%M %p'
date_format_short: '%d %b %Y'
date_format_long: '%A, %d %B, %Y'

dbicx_sugar:
  default:
    dsn: 'dbi:mysql:database=side7_v5;host=localhost'
    schema_class: 'Side7::Schema'
    user: 'side7'
    password: 'ArtIsLife'
    options:
      RaiseError: 1
      PrintError: 1
      AutoCommit: 1
      ChopBlanks: 1
      ShowErrorStatement: 1
  side7:
    alias: 'default'

plugins:
  Flash:
    token_name: 'flash'
    session_hash_key: '_flash'
  DBIC:
    default:
      dsn: 'dbi:mysql:database=side7_v5;host=localhost'
      schema_class: 'Side7::Schema'
      user: 'side7'
      password: 'ArtIsLife'
      options:
        RaiseError: 1
        PrintError: 1
        AutoCommit: 1
        ChopBlanks: 1
        ShowErrorStatement: 1
    side7:
      alias: 'default'
  Auth::Extensible:
    permission_denied_page_handler: Side7::Util::permission_denied_page_handler
    disable_roles: 0
    user_home_page: '/user'
    exit_page: '/'
    no_default_pages: 1
    mail_from: '"Side 7 Communique" <noreply@side7.com>'
    # Set to true to enable password reset code in the default handlers
    reset_password_handler: 1
    #password_generator: QP::Util::generate_user_pw # Optional random password generator
    # Set to a true value to enable recording of successful last login times
    record_lastlogin: 1
    # Password reset functionality
    password_reset_send_email: Side7::Mail::send_password_reset_email
    # create_user options
    welcome_send: Side7::Mail::send_welcome_email
    record_lastlogin: 1
    realms:
      site:
        provider: 'DBIC'
        user_as_object: 1
        schema_name: 'side7'
        users_resultset: 'User'
        roles_resultset: 'Role'
        user_roles_resultset: 'UserRole'
        users_lastlogin_column: 'lastlogin'
        users_pwresetcode_column: 'pw_reset_code'
        users_pwchanged_column: 'pw_changed'
        users_username_column: 'username'
        users_password_column: 'password'
        roles_role_column: 'role'
        roles_key: 'roles'
        encryption_algorithm: 'SHA-512'
  Ajax:
    content_type: 'application/json'

engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'
      PLUGIN_BASE: 'Side7::Template::Plugin'
      ENCODING: 'utf8'
      COMPILE_DIR: 'public/cached_files/templates'
      COMPILE_EXT: '.ttc'
      PRE_CHOMP: 0
      POST_CHOMP: 1
  session:
    YAML:
      session_dir: "./sessions"
      cookie_duration: 3600    # Default cookie timeout in seconds, 1 hour
      is_secure: 1
    Cookie:
      secret_key: 'entire works of Shakespeare'
      default_duration: 604800
